name: Issue opened

on:
  issues:
    types: 
      - opened

permissions:
  contents: read

jobs:
  notify-external:
    uses: cds-snc/design-gc-conception/.github/workflows/issue-notify-external.yml@2ba957d1122aeba2448fb2de40673142d3b24ba6
    secrets: inherit
    with:
      issue_creator: ${{ github.event.issue.user.login }}
      issue_title: ${{ github.event.issue.title }}
      issue_url: ${{ github.event.issue.html_url }}
      issue_number: ${{ github.event.issue.number }}
